### ISSUE TITLE
执行gulp -ws命令报错

### ISSUE THREAD

**Issue by maomao1127** [weui/weui#31]
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\git\weui\node_modules\browser-sync\lib\hooks.js:3:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by progrape** [comment]
报错信息显示，`browser-sync`模块引用的`lodash`模块没有找到，可能是没有安装好。可以删掉`node_modules`目录，再重新运行`npm install`安装好再试试～

**Comment by maomao1127** [comment]
果然好了
